name: Outdated

on:
  schedule:
    - cron: '00 0 * * 1'

jobs:
  outdated:
    name: Run Outdated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pipenv sync
      - name: Run Outdated
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          PAYLOAD=`cat << EOF
          {
            "attachments": [
              {
                "pretext": "bots-python's Outdated",
                "text": '$(pipenv run pip list -o --pre)'
              }
            ]
          }
          EOF`
          curl -X POST -d "payload=$PAYLOAD" $SLACK_WEBHOOK_URL
