name: Weather

on:
  schedule:
    - cron: '36 * * * *'

jobs:
  weather:
    name: Run weather
    runs-on: ubuntu-latest
    steps:
      - uses: docker://circleci/python:3.7
      - name: Run weather
        run: pipenv run python3 ./bots/weather.py
